name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    name: Batz
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v

    build:
        name: Test
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3

        - name: Use Node.js
          uses: actions/setup-node@v3
          with:
            node-version: '14'

        - name: Install dependencies
          run: npm install

        - name: Run tests
        - run: npm test
